import type { Metadata } from "next";
import { Manrope, Open_Sans } from "next/font/google";

import { Footer } from "../components/Footer";
import { cx } from "class-variance-authority";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--open-sans",
});

const manrope = Manrope({ subsets: ["latin"], variable: "--manrope" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cx(openSans.variable, manrope.variable, "bg-white")}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
